import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:shoply/app.dart';
import 'package:shoply/data/services/supabase_service.dart';
import 'package:shoply/data/services/connectivity_service.dart';
import 'package:shoply/data/services/native_oauth_service.dart';
import 'package:shoply/data/services/product_classifier_service.dart';
import 'package:shoply/data/services/gemini_categorization_service.dart';
import 'package:shoply/data/services/analytics_service.dart';
import 'package:shoply/data/services/notification_service.dart';
import 'package:shoply/data/services/fcm_service.dart';
import 'package:shoply/data/services/mascot_notification_service.dart';
import 'package:shoply/data/services/recipe_service.dart';
import 'package:shoply/data/services/app_review_service.dart';
import 'package:shoply/data/services/subscription_service.dart';
import 'package:shoply/core/services/siri_service.dart';
import 'package:shoply/core/config/env.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:io' show Platform;

/// One-time migration to add labels to recipes
Future<void> _runRecipeLabelMigration() async {
  try {
    final prefs = await SharedPreferences.getInstance();
    const migrationKey = 'recipe_labels_migration_v1';

    // Check if migration already ran
    if (prefs.getBool(migrationKey) == true) {
      debugPrint('⏭️ [MIGRATION] Recipe labels migration already completed');
      return;
    }

    debugPrint('🔄 [MIGRATION] Running one-time recipe labels migration...');
    final updatedCount = await RecipeService.instance.updateAllRecipesWithLabels();

    // Mark migration as complete
    await prefs.setBool(migrationKey, true);
    debugPrint('✅ [MIGRATION] Recipe labels migration complete - updated $updatedCount recipes');
  } catch (e) {
    debugPrint('❌ [MIGRATION] Recipe labels migration failed: $e');
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Only do the absolute minimum before runApp:
  // 1. Screen orientation
  // 2. Supabase (needed for auth/routing)
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  await SupabaseService.initialize();

  // Kick off connectivity detection before first frame so the router and
  // offline banner already have a correct online/offline value.
  unawaited(ConnectivityService.instance.initialize());

  // Launch the app immediately - everything else initializes in background
  runApp(
    const ProviderScope(
      child: AvoApp(),
    ),
  );

  // Heavy initialization happens AFTER the first frame is rendered
  _initializeServicesInBackground();
}

/// Initialize all non-critical services after the app UI is showing.
Future<void> _initializeServicesInBackground() async {
  try {
    // Firebase & Analytics
    if (Platform.isIOS || Platform.isAndroid) {
      try {
        final opts = DefaultFirebaseOptions.currentPlatform;
        if (!opts.apiKey.startsWith('YOUR_')) {
          await Firebase.initializeApp(options: opts);
          await AnalyticsService.instance.initialize();
        }
      } catch (e) {
        debugPrint('⚠️ Firebase not configured: $e');
      }
    }

    // Native OAuth
    await NativeOAuthService.initialize();

    // Product Classifier
    await ProductClassifierService.instance.initialize();

    // Gemini AI
    final geminiService = GeminiCategorizationService();
    await geminiService.initialize(Env.geminiApiKey);

    // Siri (iOS only)
    if (Platform.isIOS) {
      await SiriService().initialize();
    }

    // Notifications & Subscriptions
    if (Platform.isIOS || Platform.isAndroid) {
      await NotificationService.instance.initialize();
      await NotificationService.instance.requestPermissions();

      try {
        await FCMService.instance.initialize();
      } catch (e) {
        debugPrint('⚠️ [MAIN] FCM initialization failed: $e');
      }

      await AppReviewService.instance.trackAppOpen();
      await SubscriptionService.instance.initialize();
    }

    // Auth state listener for FCM token & migrations
    Supabase.instance.client.auth.onAuthStateChange.listen((data) async {
      final event = data.event;
      debugPrint('🔐 [AUTH] State changed: $event');

      if (event == AuthChangeEvent.signedIn && (Platform.isIOS || Platform.isAndroid)) {
        await FCMService.instance.saveTokenForCurrentUser();
        await MascotNotificationService.instance.updateLastActive();
        await MascotNotificationService.instance.checkAndSendNotification();
        _runRecipeLabelMigration();
      }
    });
  } catch (e) {
    debugPrint('⚠️ [MAIN] Background initialization error: $e');
  }
}
