-- Insert 50 Sample Recipes into Supabase
-- Run this migration to populate the recipes table
-- Schema: id (uuid), name, description, image_url, prep_time_minutes, cook_time_minutes,
--         default_servings, ingredients (jsonb), instructions (text[]), author_id (uuid),
--         author_name, labels (text[]), labels_meta (jsonb), language, translations (jsonb)

-- Create sample author UUIDs (consistent for all recipes)
DO $$
DECLARE
  chef_marco_id UUID := 'a1b2c3d4-e5f6-4789-abcd-111111111111';
  chef_isabella_id UUID := 'a1b2c3d4-e5f6-4789-abcd-222222222222';
  chef_suki_id UUID := 'a1b2c3d4-e5f6-4789-abcd-333333333333';
  chef_priya_id UUID := 'a1b2c3d4-e5f6-4789-abcd-444444444444';
  chef_chen_id UUID := 'a1b2c3d4-e5f6-4789-abcd-555555555555';
  chef_yuki_id UUID := 'a1b2c3d4-e5f6-4789-abcd-666666666666';
  chef_linh_id UUID := 'a1b2c3d4-e5f6-4789-abcd-777777777777';
  chef_kim_id UUID := 'a1b2c3d4-e5f6-4789-abcd-888888888888';
  chef_mike_id UUID := 'a1b2c3d4-e5f6-4789-abcd-999999999999';
  chef_rosa_id UUID := 'a1b2c3d4-e5f6-4789-abcd-aaaaaaaaaaaa';
  chef_nikos_id UUID := 'a1b2c3d4-e5f6-4789-abcd-bbbbbbbbbbbb';
  chef_layla_id UUID := 'a1b2c3d4-e5f6-4789-abcd-cccccccccccc';
  chef_sarah_id UUID := 'a1b2c3d4-e5f6-4789-abcd-dddddddddddd';
  chef_pierre_id UUID := 'a1b2c3d4-e5f6-4789-abcd-eeeeeeeeeeee';
BEGIN

-- Create recipes table if not exists
CREATE TABLE IF NOT EXISTS recipes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    prep_time_minutes INT DEFAULT 0,
    cook_time_minutes INT DEFAULT 0,
    default_servings INT DEFAULT 4,
    ingredients JSONB DEFAULT '[]',
    instructions JSONB DEFAULT '[]',
    author_id TEXT NOT NULL,
    author_name TEXT NOT NULL,
    author_avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    average_rating DECIMAL(3,2) DEFAULT 0,
    rating_count INT DEFAULT 0,
    labels JSONB DEFAULT '[]',
    language TEXT DEFAULT 'en'
);

-- Enable RLS
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;

-- Allow public read
DROP POLICY IF EXISTS "Recipes are publicly readable" ON recipes;
CREATE POLICY "Recipes are publicly readable" ON recipes FOR SELECT USING (true);

-- Insert 50 Recipes
-- ITALIAN (1-5)
INSERT INTO recipes (id, name, description, image_url, prep_time_minutes, cook_time_minutes, default_servings, ingredients, instructions, author_id, author_name, labels) VALUES
('recipe_001', 'Spaghetti Carbonara', 'Classic Italian pasta with creamy egg-cheese sauce and crispy bacon.', 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800', 10, 15, 4, '[{"name":"Spaghetti","amount":400,"unit":"g"},{"name":"Pancetta","amount":200,"unit":"g"},{"name":"Eggs","amount":4,"unit":"pcs"},{"name":"Parmesan","amount":100,"unit":"g"},{"name":"Black pepper","amount":1,"unit":"tsp"}]', '["Cook spaghetti in salted water until al dente","Dice pancetta and fry until crispy","Beat eggs with grated parmesan and pepper","Drain pasta, reserving some water","Toss hot pasta with pancetta off heat","Add egg mixture, stirring quickly to create creamy sauce"]', 'chef_001', 'Chef Marco',  '["italian","pasta","quick","dinner"]'),

('recipe_002', 'Margherita Pizza', 'Authentic Neapolitan pizza with San Marzano tomatoes, fresh mozzarella, and basil.', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800', 120, 15, 2, '[{"name":"Pizza flour","amount":500,"unit":"g"},{"name":"Yeast","amount":7,"unit":"g"},{"name":"San Marzano tomatoes","amount":400,"unit":"g"},{"name":"Fresh mozzarella","amount":250,"unit":"g"},{"name":"Fresh basil","amount":10,"unit":"leaves"}]', '["Mix flour, yeast, salt, and water to form dough","Knead for 10 minutes until smooth","Let rise for 2 hours","Preheat oven to highest setting","Stretch dough into round shape","Top with crushed tomatoes and mozzarella","Bake for 10-15 minutes until crust is golden","Add fresh basil"]', 'chef_001', 'Chef Marco',  '["italian","pizza","vegetarian","dinner"]'),

('recipe_003', 'Risotto ai Funghi', 'Creamy Italian risotto with mixed wild mushrooms and parmesan.', 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800', 15, 30, 4, '[{"name":"Arborio rice","amount":320,"unit":"g"},{"name":"Mixed mushrooms","amount":300,"unit":"g"},{"name":"Vegetable stock","amount":1000,"unit":"ml"},{"name":"White wine","amount":150,"unit":"ml"},{"name":"Parmesan","amount":80,"unit":"g"},{"name":"Butter","amount":50,"unit":"g"}]', '["Sauté mushrooms in butter, set aside","Sauté shallots until soft","Add rice and toast for 2 minutes","Add wine and stir until absorbed","Add stock one ladle at a time, stirring constantly","After 18 minutes, add mushrooms","Finish with butter and parmesan"]', 'chef_001', 'Chef Marco',  '["italian","risotto","vegetarian","dinner"]'),

('recipe_004', 'Tiramisu', 'Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800', 30, 0, 8, '[{"name":"Mascarpone","amount":500,"unit":"g"},{"name":"Ladyfingers","amount":300,"unit":"g"},{"name":"Espresso","amount":300,"unit":"ml"},{"name":"Eggs","amount":4,"unit":"pcs"},{"name":"Sugar","amount":100,"unit":"g"},{"name":"Cocoa powder","amount":30,"unit":"g"}]', '["Separate eggs, beat yolks with sugar until pale","Fold in mascarpone until smooth","Beat egg whites until stiff, fold into mascarpone","Dip ladyfingers briefly in cooled espresso","Layer ladyfingers and cream in dish","Refrigerate for at least 4 hours","Dust with cocoa powder before serving"]', 'chef_002', 'Chef Isabella',  '["italian","dessert","no-bake","coffee"]'),

('recipe_005', 'Lasagna Bolognese', 'Traditional layered pasta with rich meat sauce and béchamel.', 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800', 45, 60, 8, '[{"name":"Lasagna sheets","amount":500,"unit":"g"},{"name":"Ground beef","amount":500,"unit":"g"},{"name":"Tomato passata","amount":800,"unit":"g"},{"name":"Béchamel sauce","amount":500,"unit":"ml"},{"name":"Parmesan","amount":100,"unit":"g"},{"name":"Onion","amount":1,"unit":"pc"}]', '["Make bolognese sauce with beef and tomatoes","Prepare béchamel sauce","Layer pasta, meat sauce, béchamel","Repeat layers 3-4 times","Top with parmesan","Bake at 180°C for 45 minutes"]', 'chef_002', 'Chef Isabella',  '["italian","pasta","beef","dinner"]')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url;

-- ASIAN (6-15)
INSERT INTO recipes (id, name, description, image_url, prep_time_minutes, cook_time_minutes, default_servings, ingredients, instructions, author_id, author_name, labels) VALUES
('recipe_006', 'Chicken Pad Thai', 'Classic Thai stir-fried rice noodles with chicken, eggs, and peanuts.', 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800', 20, 15, 4, '[{"name":"Rice noodles","amount":250,"unit":"g"},{"name":"Chicken breast","amount":300,"unit":"g"},{"name":"Eggs","amount":2,"unit":"pcs"},{"name":"Bean sprouts","amount":150,"unit":"g"},{"name":"Peanuts","amount":50,"unit":"g"},{"name":"Fish sauce","amount":3,"unit":"tbsp"}]', '["Soak rice noodles in warm water for 30 minutes","Mix fish sauce, tamarind, and sugar for sauce","Stir-fry chicken until cooked, set aside","Scramble eggs, set aside","Stir-fry drained noodles with sauce","Add chicken, eggs, and bean sprouts","Top with peanuts and lime wedges"]', 'chef_003', 'Chef Suki',  '["thai","asian","noodles","dinner","quick"]'),

('recipe_007', 'Chicken Tikka Masala', 'Tender chicken in rich, creamy tomato-based curry sauce with Indian spices.', 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800', 30, 30, 4, '[{"name":"Chicken thighs","amount":600,"unit":"g"},{"name":"Yogurt","amount":200,"unit":"ml"},{"name":"Tomato passata","amount":400,"unit":"g"},{"name":"Heavy cream","amount":200,"unit":"ml"},{"name":"Garam masala","amount":2,"unit":"tbsp"},{"name":"Ginger","amount":30,"unit":"g"}]', '["Marinate chicken in yogurt and spices for 1 hour","Grill or pan-fry chicken until charred","Sauté onions, garlic, and ginger","Add spices and cook until fragrant","Add tomato passata and simmer","Add cream and chicken, simmer 10 minutes","Serve with basmati rice or naan"]', 'chef_004', 'Chef Priya',  '["indian","curry","chicken","dinner","spicy"]'),

('recipe_008', 'Vegetable Fried Rice', 'Quick and easy Chinese-style fried rice with colorful vegetables.', 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800', 15, 10, 4, '[{"name":"Cooked rice","amount":600,"unit":"g"},{"name":"Eggs","amount":3,"unit":"pcs"},{"name":"Mixed vegetables","amount":200,"unit":"g"},{"name":"Soy sauce","amount":3,"unit":"tbsp"},{"name":"Sesame oil","amount":1,"unit":"tbsp"},{"name":"Green onions","amount":4,"unit":"stalks"}]', '["Use day-old rice for best results","Scramble eggs in hot wok, set aside","Stir-fry vegetables until tender-crisp","Add rice and break up any clumps","Add soy sauce and toss well","Add eggs and green onions","Finish with sesame oil"]', 'chef_005', 'Chef Chen',  '["chinese","asian","vegetarian","quick","rice"]'),

('recipe_009', 'Sushi Rolls', 'Homemade maki sushi with fresh fish and vegetables.', 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800', 45, 20, 4, '[{"name":"Sushi rice","amount":400,"unit":"g"},{"name":"Nori sheets","amount":8,"unit":"pcs"},{"name":"Fresh salmon","amount":200,"unit":"g"},{"name":"Cucumber","amount":1,"unit":"pc"},{"name":"Avocado","amount":1,"unit":"pc"},{"name":"Rice vinegar","amount":60,"unit":"ml"}]', '["Cook rice and season with rice vinegar","Let rice cool to room temperature","Cut fish and vegetables into strips","Place nori on bamboo mat","Spread rice evenly, leaving edge free","Add fillings in a line","Roll tightly using the mat","Cut into 6-8 pieces with wet knife"]', 'chef_006', 'Chef Yuki',  '["japanese","asian","seafood","healthy"]'),

('recipe_010', 'Beef Pho', 'Traditional Vietnamese beef noodle soup with aromatic broth.', 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800', 30, 180, 6, '[{"name":"Beef bones","amount":1000,"unit":"g"},{"name":"Rice noodles","amount":400,"unit":"g"},{"name":"Beef sirloin","amount":300,"unit":"g"},{"name":"Star anise","amount":3,"unit":"pcs"},{"name":"Fish sauce","amount":3,"unit":"tbsp"},{"name":"Thai basil","amount":1,"unit":"bunch"}]', '["Char onion and ginger over flame","Simmer beef bones with spices for 3 hours","Strain broth and season with fish sauce","Cook rice noodles according to package","Slice beef paper-thin","Assemble noodles and raw beef in bowls","Ladle hot broth over to cook beef","Serve with fresh herbs and lime"]', 'chef_007', 'Chef Linh',  '["vietnamese","asian","soup","beef"]'),

('recipe_011', 'Korean Bibimbap', 'Colorful Korean rice bowl with vegetables, beef, and gochujang sauce.', 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800', 30, 20, 4, '[{"name":"Short grain rice","amount":400,"unit":"g"},{"name":"Ground beef","amount":200,"unit":"g"},{"name":"Spinach","amount":200,"unit":"g"},{"name":"Carrots","amount":2,"unit":"pcs"},{"name":"Eggs","amount":4,"unit":"pcs"},{"name":"Gochujang","amount":4,"unit":"tbsp"}]', '["Cook rice and keep warm","Sauté each vegetable separately with sesame oil","Season beef with soy sauce and garlic, cook","Fry eggs sunny-side up","Arrange rice in bowls","Top with vegetables and beef in sections","Add fried egg on top","Serve with gochujang on the side"]', 'chef_008', 'Chef Kim',  '["korean","asian","rice","beef","healthy"]'),

('recipe_012', 'Ramen', 'Rich Japanese noodle soup with pork broth and soft-boiled egg.', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800', 30, 240, 4, '[{"name":"Ramen noodles","amount":400,"unit":"g"},{"name":"Pork belly","amount":300,"unit":"g"},{"name":"Eggs","amount":4,"unit":"pcs"},{"name":"Soy sauce","amount":4,"unit":"tbsp"},{"name":"Miso paste","amount":2,"unit":"tbsp"},{"name":"Green onions","amount":4,"unit":"stalks"}]', '["Simmer pork bones for rich broth","Braise pork belly until tender","Soft-boil eggs, marinate in soy sauce","Cook ramen noodles","Assemble with broth, noodles, pork","Add egg and toppings"]', 'chef_006', 'Chef Yuki',  '["japanese","asian","soup","pork"]'),

('recipe_013', 'Green Curry', 'Aromatic Thai green curry with chicken and vegetables.', 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800', 20, 25, 4, '[{"name":"Chicken thighs","amount":500,"unit":"g"},{"name":"Green curry paste","amount":3,"unit":"tbsp"},{"name":"Coconut milk","amount":400,"unit":"ml"},{"name":"Thai basil","amount":1,"unit":"bunch"},{"name":"Bamboo shoots","amount":200,"unit":"g"},{"name":"Fish sauce","amount":2,"unit":"tbsp"}]', '["Cut chicken into pieces","Fry curry paste until fragrant","Add coconut cream and chicken","Simmer until chicken is cooked","Add vegetables and remaining coconut milk","Season with fish sauce and palm sugar","Finish with Thai basil"]', 'chef_003', 'Chef Suki',  '["thai","asian","curry","chicken","spicy"]'),

('recipe_014', 'Kung Pao Chicken', 'Spicy Sichuan stir-fry with chicken, peanuts, and chilies.', 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800', 20, 15, 4, '[{"name":"Chicken breast","amount":500,"unit":"g"},{"name":"Peanuts","amount":100,"unit":"g"},{"name":"Dried chilies","amount":10,"unit":"pcs"},{"name":"Sichuan peppercorns","amount":1,"unit":"tbsp"},{"name":"Soy sauce","amount":3,"unit":"tbsp"},{"name":"Rice vinegar","amount":2,"unit":"tbsp"}]', '["Cube chicken and marinate","Toast peanuts and set aside","Stir-fry chilies and peppercorns","Add chicken and cook through","Add sauce mixture","Toss with peanuts and green onions"]', 'chef_005', 'Chef Chen',  '["chinese","asian","chicken","spicy"]'),

('recipe_015', 'Teriyaki Salmon', 'Glazed salmon fillets with sweet teriyaki sauce.', 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800', 10, 15, 4, '[{"name":"Salmon fillets","amount":4,"unit":"pcs"},{"name":"Soy sauce","amount":4,"unit":"tbsp"},{"name":"Mirin","amount":3,"unit":"tbsp"},{"name":"Sugar","amount":2,"unit":"tbsp"},{"name":"Ginger","amount":20,"unit":"g"},{"name":"Sesame seeds","amount":1,"unit":"tbsp"}]', '["Make teriyaki sauce with soy, mirin, sugar","Pan-sear salmon skin-side down","Flip and add sauce to pan","Glaze salmon while cooking","Garnish with sesame seeds","Serve with rice"]', 'chef_006', 'Chef Yuki',  '["japanese","asian","seafood","healthy","quick"]')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url;

-- AMERICAN & MEXICAN (16-25)
INSERT INTO recipes (id, name, description, image_url, prep_time_minutes, cook_time_minutes, default_servings, ingredients, instructions, author_id, author_name, labels) VALUES
('recipe_016', 'Classic Cheeseburger', 'Juicy beef patty with melted cheese and fresh toppings.', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800', 15, 10, 4, '[{"name":"Ground beef","amount":500,"unit":"g"},{"name":"Burger buns","amount":4,"unit":"pcs"},{"name":"Cheddar cheese","amount":4,"unit":"slices"},{"name":"Lettuce","amount":4,"unit":"leaves"},{"name":"Tomato","amount":1,"unit":"pc"},{"name":"Onion","amount":1,"unit":"pc"}]', '["Season beef and form into patties","Grill patties to desired doneness","Add cheese in last minute","Toast buns on grill","Assemble with toppings","Serve with fries"]', 'chef_009', 'Chef Mike',  '["american","beef","dinner","comfort-food"]'),

('recipe_017', 'Beef Tacos', 'Authentic Mexican street tacos with seasoned beef.', 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800', 20, 15, 4, '[{"name":"Ground beef","amount":400,"unit":"g"},{"name":"Corn tortillas","amount":12,"unit":"pcs"},{"name":"Onion","amount":1,"unit":"pc"},{"name":"Cilantro","amount":1,"unit":"bunch"},{"name":"Lime","amount":2,"unit":"pcs"},{"name":"Taco seasoning","amount":2,"unit":"tbsp"}]', '["Cook beef with seasoning","Warm tortillas","Dice onion and cilantro","Assemble tacos","Squeeze lime on top","Serve with salsa"]', 'chef_010', 'Chef Rosa',  '["mexican","beef","quick","dinner"]'),

('recipe_018', 'Chicken Quesadilla', 'Crispy tortilla filled with chicken and melted cheese.', 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800', 15, 10, 4, '[{"name":"Flour tortillas","amount":4,"unit":"pcs"},{"name":"Cooked chicken","amount":300,"unit":"g"},{"name":"Cheese","amount":200,"unit":"g"},{"name":"Bell peppers","amount":2,"unit":"pcs"},{"name":"Sour cream","amount":100,"unit":"ml"}]', '["Shred chicken","Sauté peppers","Place tortilla in pan","Add cheese, chicken, peppers","Fold and cook until golden","Cut and serve with sour cream"]', 'chef_010', 'Chef Rosa',  '["mexican","chicken","quick","dinner"]'),

('recipe_019', 'BBQ Ribs', 'Fall-off-the-bone tender ribs with homemade BBQ sauce.', 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800', 30, 180, 6, '[{"name":"Pork ribs","amount":2,"unit":"kg"},{"name":"BBQ sauce","amount":400,"unit":"ml"},{"name":"Brown sugar","amount":100,"unit":"g"},{"name":"Paprika","amount":2,"unit":"tbsp"},{"name":"Garlic powder","amount":1,"unit":"tbsp"}]', '["Remove membrane from ribs","Apply dry rub generously","Wrap in foil and bake at 150C for 2.5 hours","Unwrap and brush with BBQ sauce","Grill or broil to caramelize","Rest before cutting"]', 'chef_009', 'Chef Mike',  '["american","pork","bbq","dinner"]'),

('recipe_020', 'Guacamole', 'Fresh and creamy avocado dip with lime and cilantro.', 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800', 15, 0, 6, '[{"name":"Avocados","amount":3,"unit":"pcs"},{"name":"Lime","amount":2,"unit":"pcs"},{"name":"Cilantro","amount":1,"unit":"bunch"},{"name":"Red onion","amount":0.5,"unit":"pc"},{"name":"Jalapeño","amount":1,"unit":"pc"},{"name":"Salt","amount":1,"unit":"tsp"}]', '["Halve and pit avocados","Mash to desired consistency","Add lime juice immediately","Fold in diced onion and jalapeño","Add chopped cilantro","Season with salt"]', 'chef_010', 'Chef Rosa',  '["mexican","vegetarian","quick","healthy","vegan"]'),

('recipe_021', 'Mac and Cheese', 'Creamy baked macaroni with three cheese blend.', 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800', 15, 25, 6, '[{"name":"Macaroni","amount":400,"unit":"g"},{"name":"Cheddar cheese","amount":300,"unit":"g"},{"name":"Gruyère","amount":100,"unit":"g"},{"name":"Milk","amount":500,"unit":"ml"},{"name":"Butter","amount":50,"unit":"g"},{"name":"Breadcrumbs","amount":50,"unit":"g"}]', '["Cook pasta al dente","Make roux with butter and flour","Add milk and cook until thick","Stir in cheeses until melted","Combine with pasta","Top with breadcrumbs and bake"]', 'chef_009', 'Chef Mike',  '["american","pasta","vegetarian","comfort-food"]'),

('recipe_022', 'Chicken Enchiladas', 'Rolled tortillas with chicken in red chile sauce.', 'https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800', 30, 25, 6, '[{"name":"Flour tortillas","amount":8,"unit":"pcs"},{"name":"Shredded chicken","amount":500,"unit":"g"},{"name":"Enchilada sauce","amount":500,"unit":"ml"},{"name":"Cheese","amount":250,"unit":"g"},{"name":"Sour cream","amount":150,"unit":"ml"},{"name":"Onion","amount":1,"unit":"pc"}]', '["Mix chicken with some sauce and cheese","Fill tortillas and roll","Place in baking dish","Cover with remaining sauce and cheese","Bake at 180C for 20 minutes","Serve with sour cream"]', 'chef_010', 'Chef Rosa',  '["mexican","chicken","dinner","comfort-food"]'),

('recipe_023', 'Buffalo Wings', 'Crispy chicken wings tossed in spicy buffalo sauce.', 'https://images.unsplash.com/photo-1608039829572-9b0e16f88ed0?w=800', 15, 45, 4, '[{"name":"Chicken wings","amount":1,"unit":"kg"},{"name":"Hot sauce","amount":150,"unit":"ml"},{"name":"Butter","amount":75,"unit":"g"},{"name":"Garlic powder","amount":1,"unit":"tsp"},{"name":"Blue cheese dressing","amount":150,"unit":"ml"}]', '["Pat wings dry","Bake at 200C for 40 minutes, flipping once","Melt butter with hot sauce","Toss crispy wings in sauce","Serve with blue cheese and celery"]', 'chef_009', 'Chef Mike',  '["american","chicken","spicy","appetizer"]'),

('recipe_024', 'Churros', 'Crispy fried dough with cinnamon sugar coating.', 'https://images.unsplash.com/photo-1624371414361-e670eeba9a5c?w=800', 20, 15, 6, '[{"name":"Flour","amount":250,"unit":"g"},{"name":"Water","amount":250,"unit":"ml"},{"name":"Butter","amount":75,"unit":"g"},{"name":"Sugar","amount":100,"unit":"g"},{"name":"Cinnamon","amount":2,"unit":"tsp"},{"name":"Oil for frying","amount":500,"unit":"ml"}]', '["Boil water with butter","Add flour and stir vigorously","Cool slightly, add eggs","Pipe into hot oil","Fry until golden","Roll in cinnamon sugar"]', 'chef_010', 'Chef Rosa',  '["mexican","dessert","sweet"]'),

('recipe_025', 'Clam Chowder', 'Creamy New England style soup with clams and potatoes.', 'https://images.unsplash.com/photo-1594756202469-9ff9799b2e4e?w=800', 20, 30, 6, '[{"name":"Clams","amount":500,"unit":"g"},{"name":"Potatoes","amount":400,"unit":"g"},{"name":"Heavy cream","amount":300,"unit":"ml"},{"name":"Bacon","amount":150,"unit":"g"},{"name":"Onion","amount":1,"unit":"pc"},{"name":"Celery","amount":2,"unit":"stalks"}]', '["Cook bacon until crispy","Sauté vegetables in bacon fat","Add potatoes and clam juice","Simmer until potatoes are tender","Add cream and clams","Heat through and serve"]', 'chef_009', 'Chef Mike',  '["american","soup","seafood","comfort-food"]')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url;

-- MEDITERRANEAN & MIDDLE EASTERN (26-35)
INSERT INTO recipes (id, name, description, image_url, prep_time_minutes, cook_time_minutes, default_servings, ingredients, instructions, author_id, author_name, labels) VALUES
('recipe_026', 'Greek Salad', 'Fresh Mediterranean salad with feta and olives.', 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800', 15, 0, 4, '[{"name":"Cucumber","amount":1,"unit":"pc"},{"name":"Tomatoes","amount":4,"unit":"pcs"},{"name":"Red onion","amount":0.5,"unit":"pc"},{"name":"Feta cheese","amount":200,"unit":"g"},{"name":"Kalamata olives","amount":100,"unit":"g"},{"name":"Olive oil","amount":60,"unit":"ml"}]', '["Chop vegetables into chunks","Slice onion thinly","Arrange on platter","Top with feta and olives","Drizzle with olive oil","Season with oregano"]', 'chef_011', 'Chef Nikos',  '["greek","vegetarian","healthy","quick","salad"]'),

('recipe_027', 'Falafel', 'Crispy chickpea fritters with herbs and spices.', 'https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?w=800', 30, 15, 6, '[{"name":"Dried chickpeas","amount":400,"unit":"g"},{"name":"Fresh parsley","amount":1,"unit":"bunch"},{"name":"Cilantro","amount":1,"unit":"bunch"},{"name":"Garlic","amount":4,"unit":"cloves"},{"name":"Cumin","amount":2,"unit":"tsp"},{"name":"Coriander","amount":2,"unit":"tsp"}]', '["Soak chickpeas overnight","Blend with herbs and spices","Form into balls","Fry until golden brown","Serve in pita with tahini","Add pickled vegetables"]', 'chef_012', 'Chef Layla',  '["middle-eastern","vegetarian","vegan","healthy"]'),

('recipe_028', 'Hummus', 'Smooth chickpea dip with tahini and lemon.', 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=800', 15, 0, 8, '[{"name":"Chickpeas","amount":400,"unit":"g"},{"name":"Tahini","amount":100,"unit":"g"},{"name":"Lemon juice","amount":60,"unit":"ml"},{"name":"Garlic","amount":2,"unit":"cloves"},{"name":"Olive oil","amount":60,"unit":"ml"},{"name":"Cumin","amount":1,"unit":"tsp"}]', '["Blend chickpeas until smooth","Add tahini and lemon juice","Add garlic and cumin","Drizzle in olive oil while blending","Season to taste","Serve with pita and olive oil drizzle"]', 'chef_012', 'Chef Layla',  '["middle-eastern","vegetarian","vegan","healthy","quick"]'),

('recipe_029', 'Moussaka', 'Layered Greek casserole with eggplant and meat sauce.', 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800', 45, 60, 8, '[{"name":"Eggplants","amount":3,"unit":"pcs"},{"name":"Ground lamb","amount":500,"unit":"g"},{"name":"Onion","amount":2,"unit":"pcs"},{"name":"Tomato sauce","amount":400,"unit":"g"},{"name":"Béchamel","amount":500,"unit":"ml"},{"name":"Parmesan","amount":100,"unit":"g"}]', '["Slice and salt eggplants","Pan-fry until golden","Make meat sauce with lamb and tomatoes","Layer eggplant and meat sauce","Top with béchamel and cheese","Bake at 180C for 45 minutes"]', 'chef_011', 'Chef Nikos',  '["greek","beef","dinner","comfort-food"]'),

('recipe_030', 'Shakshuka', 'Eggs poached in spiced tomato sauce.', 'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800', 10, 20, 4, '[{"name":"Eggs","amount":6,"unit":"pcs"},{"name":"Tomatoes","amount":400,"unit":"g"},{"name":"Bell peppers","amount":2,"unit":"pcs"},{"name":"Onion","amount":1,"unit":"pc"},{"name":"Cumin","amount":1,"unit":"tsp"},{"name":"Paprika","amount":1,"unit":"tsp"}]', '["Sauté onions and peppers","Add spices and cook briefly","Add tomatoes and simmer","Make wells and crack in eggs","Cover and cook until eggs set","Serve with crusty bread"]', 'chef_012', 'Chef Layla',  '["middle-eastern","vegetarian","frühstück","healthy"]'),

('recipe_031', 'Gyros', 'Greek meat wrap with tzatziki sauce.', 'https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800', 30, 20, 4, '[{"name":"Lamb or chicken","amount":500,"unit":"g"},{"name":"Pita bread","amount":4,"unit":"pcs"},{"name":"Tzatziki","amount":200,"unit":"ml"},{"name":"Tomatoes","amount":2,"unit":"pcs"},{"name":"Red onion","amount":1,"unit":"pc"},{"name":"Greek seasoning","amount":2,"unit":"tbsp"}]', '["Marinate meat with seasoning","Cook meat until done","Warm pita bread","Slice meat thinly","Assemble with vegetables and tzatziki","Wrap and serve"]', 'chef_011', 'Chef Nikos',  '["greek","dinner","quick"]'),

('recipe_032', 'Baklava', 'Sweet pastry with nuts and honey syrup.', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800', 45, 45, 12, '[{"name":"Phyllo dough","amount":500,"unit":"g"},{"name":"Walnuts","amount":300,"unit":"g"},{"name":"Butter","amount":200,"unit":"g"},{"name":"Honey","amount":200,"unit":"ml"},{"name":"Sugar","amount":200,"unit":"g"},{"name":"Cinnamon","amount":2,"unit":"tsp"}]', '["Layer phyllo with melted butter","Add nut mixture between layers","Cut into diamonds before baking","Bake at 180C until golden","Make honey syrup","Pour over hot baklava"]', 'chef_011', 'Chef Nikos',  '["greek","dessert","sweet"]'),

('recipe_033', 'Tabbouleh', 'Fresh Lebanese parsley salad with bulgur.', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', 20, 0, 6, '[{"name":"Bulgur wheat","amount":100,"unit":"g"},{"name":"Fresh parsley","amount":3,"unit":"bunches"},{"name":"Tomatoes","amount":3,"unit":"pcs"},{"name":"Lemon juice","amount":80,"unit":"ml"},{"name":"Olive oil","amount":60,"unit":"ml"},{"name":"Mint","amount":1,"unit":"bunch"}]', '["Soak bulgur in water","Chop parsley very finely","Dice tomatoes small","Mix bulgur with herbs","Add lemon juice and oil","Season and chill before serving"]', 'chef_012', 'Chef Layla',  '["middle-eastern","vegetarian","vegan","healthy","salad"]'),

('recipe_034', 'Spanakopita', 'Greek spinach and feta pie in phyllo.', 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800', 30, 45, 8, '[{"name":"Spinach","amount":500,"unit":"g"},{"name":"Feta cheese","amount":300,"unit":"g"},{"name":"Phyllo dough","amount":400,"unit":"g"},{"name":"Onions","amount":2,"unit":"pcs"},{"name":"Dill","amount":1,"unit":"bunch"},{"name":"Butter","amount":150,"unit":"g"}]', '["Sauté onions and spinach","Cool and mix with feta and herbs","Layer phyllo with butter","Add filling","Top with more phyllo layers","Bake until golden"]', 'chef_011', 'Chef Nikos',  '["greek","vegetarian","dinner"]'),

('recipe_035', 'Lamb Kofta', 'Spiced Middle Eastern lamb kebabs.', 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800', 25, 15, 4, '[{"name":"Ground lamb","amount":500,"unit":"g"},{"name":"Onion","amount":1,"unit":"pc"},{"name":"Parsley","amount":1,"unit":"bunch"},{"name":"Cumin","amount":2,"unit":"tsp"},{"name":"Coriander","amount":2,"unit":"tsp"},{"name":"Garlic","amount":3,"unit":"cloves"}]', '["Mix lamb with grated onion","Add herbs and spices","Form onto skewers","Grill until cooked through","Serve with rice and yogurt","Garnish with fresh herbs"]', 'chef_012', 'Chef Layla',  '["middle-eastern","dinner","healthy"]')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url;

-- BREAKFAST & BRUNCH (36-42)
INSERT INTO recipes (id, name, description, image_url, prep_time_minutes, cook_time_minutes, default_servings, ingredients, instructions, author_id, author_name, labels) VALUES
('recipe_036', 'Pancakes', 'Fluffy American-style pancakes with maple syrup.', 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800', 10, 15, 4, '[{"name":"Flour","amount":250,"unit":"g"},{"name":"Milk","amount":300,"unit":"ml"},{"name":"Eggs","amount":2,"unit":"pcs"},{"name":"Butter","amount":50,"unit":"g"},{"name":"Sugar","amount":2,"unit":"tbsp"},{"name":"Baking powder","amount":2,"unit":"tsp"}]', '["Mix dry ingredients","Combine wet ingredients","Fold together gently","Cook on buttered pan","Flip when bubbles form","Serve with maple syrup"]', 'chef_013', 'Chef Sarah',  '["american","frühstück","vegetarian","sweet"]'),

('recipe_037', 'Eggs Benedict', 'Poached eggs with hollandaise on English muffins.', 'https://images.unsplash.com/photo-1608039829572-9b0e16f88ed0?w=800', 20, 15, 4, '[{"name":"English muffins","amount":4,"unit":"pcs"},{"name":"Eggs","amount":8,"unit":"pcs"},{"name":"Ham","amount":8,"unit":"slices"},{"name":"Butter","amount":150,"unit":"g"},{"name":"Egg yolks","amount":3,"unit":"pcs"},{"name":"Lemon juice","amount":1,"unit":"tbsp"}]', '["Make hollandaise with yolks, butter, lemon","Poach eggs in simmering water","Toast muffins","Layer ham and poached eggs","Top with hollandaise","Serve immediately"]', 'chef_013', 'Chef Sarah',  '["american","frühstück","eggs"]'),

('recipe_038', 'Avocado Toast', 'Trendy breakfast with mashed avocado on toast.', 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800', 10, 5, 2, '[{"name":"Sourdough bread","amount":2,"unit":"slices"},{"name":"Avocado","amount":1,"unit":"pc"},{"name":"Eggs","amount":2,"unit":"pcs"},{"name":"Cherry tomatoes","amount":100,"unit":"g"},{"name":"Chili flakes","amount":1,"unit":"tsp"},{"name":"Lime","amount":0.5,"unit":"pc"}]', '["Toast bread until golden","Mash avocado with lime","Spread on toast","Top with poached egg","Add tomatoes and chili flakes","Season with salt and pepper"]', 'chef_013', 'Chef Sarah',  '["frühstück","vegetarian","healthy","quick"]'),

('recipe_039', 'French Toast', 'Custard-soaked bread pan-fried to perfection.', 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800', 10, 15, 4, '[{"name":"Brioche","amount":8,"unit":"slices"},{"name":"Eggs","amount":4,"unit":"pcs"},{"name":"Milk","amount":200,"unit":"ml"},{"name":"Vanilla","amount":1,"unit":"tsp"},{"name":"Cinnamon","amount":1,"unit":"tsp"},{"name":"Butter","amount":50,"unit":"g"}]', '["Whisk eggs, milk, vanilla, cinnamon","Soak bread slices","Fry in butter until golden","Flip and cook other side","Serve with berries and maple syrup","Dust with powdered sugar"]', 'chef_013', 'Chef Sarah',  '["frühstück","vegetarian","sweet"]'),

('recipe_040', 'Granola Bowl', 'Healthy breakfast bowl with yogurt and fresh fruit.', 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800', 10, 0, 2, '[{"name":"Greek yogurt","amount":400,"unit":"g"},{"name":"Granola","amount":100,"unit":"g"},{"name":"Berries","amount":200,"unit":"g"},{"name":"Honey","amount":2,"unit":"tbsp"},{"name":"Banana","amount":1,"unit":"pc"},{"name":"Chia seeds","amount":1,"unit":"tbsp"}]', '["Divide yogurt into bowls","Top with granola","Add fresh berries and banana","Drizzle with honey","Sprinkle chia seeds","Serve immediately"]', 'chef_013', 'Chef Sarah',  '["frühstück","vegetarian","healthy","quick"]'),

('recipe_041', 'Breakfast Burrito', 'Hearty wrap with eggs, cheese, and breakfast meats.', 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800', 15, 15, 4, '[{"name":"Flour tortillas","amount":4,"unit":"pcs"},{"name":"Eggs","amount":6,"unit":"pcs"},{"name":"Bacon","amount":8,"unit":"strips"},{"name":"Cheese","amount":150,"unit":"g"},{"name":"Potatoes","amount":200,"unit":"g"},{"name":"Salsa","amount":100,"unit":"ml"}]', '["Cook bacon until crispy","Fry cubed potatoes","Scramble eggs","Warm tortillas","Layer ingredients in tortilla","Roll and serve with salsa"]', 'chef_009', 'Chef Mike',  '["american","frühstück","eggs"]'),

('recipe_042', 'Overnight Oats', 'No-cook creamy oats prepared the night before.', 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800', 10, 0, 2, '[{"name":"Rolled oats","amount":100,"unit":"g"},{"name":"Milk","amount":200,"unit":"ml"},{"name":"Greek yogurt","amount":100,"unit":"g"},{"name":"Honey","amount":2,"unit":"tbsp"},{"name":"Berries","amount":100,"unit":"g"},{"name":"Chia seeds","amount":1,"unit":"tbsp"}]', '["Mix oats with milk and yogurt","Add honey and chia seeds","Cover and refrigerate overnight","In morning, add toppings","Enjoy cold or microwaved","Perfect for meal prep"]', 'chef_013', 'Chef Sarah',  '["frühstück","vegetarian","healthy","quick"]')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url;

-- DESSERTS & SWEET (43-50)
INSERT INTO recipes (id, name, description, image_url, prep_time_minutes, cook_time_minutes, default_servings, ingredients, instructions, author_id, author_name, labels) VALUES
('recipe_043', 'Chocolate Lava Cake', 'Decadent molten chocolate cake with gooey center.', 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800', 15, 12, 4, '[{"name":"Dark chocolate","amount":200,"unit":"g"},{"name":"Butter","amount":100,"unit":"g"},{"name":"Eggs","amount":4,"unit":"pcs"},{"name":"Sugar","amount":100,"unit":"g"},{"name":"Flour","amount":50,"unit":"g"}]', '["Melt chocolate and butter","Whisk eggs with sugar","Fold in chocolate mixture","Add flour gently","Bake at 200C for exactly 12 minutes","Serve immediately"]', 'chef_002', 'Chef Isabella',  '["dessert","chocolate","sweet"]'),

('recipe_044', 'Crème Brûlée', 'Classic French custard with caramelized sugar top.', 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=800', 20, 45, 6, '[{"name":"Heavy cream","amount":500,"unit":"ml"},{"name":"Egg yolks","amount":6,"unit":"pcs"},{"name":"Sugar","amount":120,"unit":"g"},{"name":"Vanilla bean","amount":1,"unit":"pc"}]', '["Heat cream with vanilla","Whisk yolks with sugar","Temper yolks with hot cream","Pour into ramekins","Bake in water bath","Chill, then torch sugar on top"]', 'chef_014', 'Chef Pierre',  '["french","dessert","sweet"]'),

('recipe_045', 'New York Cheesecake', 'Rich and creamy classic American cheesecake.', 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=800', 30, 60, 12, '[{"name":"Cream cheese","amount":900,"unit":"g"},{"name":"Sugar","amount":200,"unit":"g"},{"name":"Eggs","amount":4,"unit":"pcs"},{"name":"Sour cream","amount":200,"unit":"ml"},{"name":"Graham crackers","amount":200,"unit":"g"},{"name":"Butter","amount":100,"unit":"g"}]', '["Make crust with crackers and butter","Beat cream cheese until smooth","Add sugar, then eggs one at a time","Add sour cream","Bake at 160C for 1 hour","Cool slowly to prevent cracks"]', 'chef_013', 'Chef Sarah',  '["american","dessert","sweet"]'),

('recipe_046', 'Apple Pie', 'Classic American pie with cinnamon-spiced apples.', 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800', 45, 55, 8, '[{"name":"Apples","amount":1,"unit":"kg"},{"name":"Pie crust","amount":2,"unit":"pcs"},{"name":"Sugar","amount":150,"unit":"g"},{"name":"Cinnamon","amount":2,"unit":"tsp"},{"name":"Butter","amount":30,"unit":"g"},{"name":"Lemon juice","amount":1,"unit":"tbsp"}]', '["Slice apples and toss with sugar and spices","Line pie dish with crust","Fill with apple mixture","Dot with butter","Cover with top crust","Bake at 190C until golden"]', 'chef_013', 'Chef Sarah',  '["american","dessert","sweet","fruit"]'),

('recipe_047', 'Panna Cotta', 'Silky Italian cream dessert with berry sauce.', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800', 15, 0, 6, '[{"name":"Heavy cream","amount":500,"unit":"ml"},{"name":"Sugar","amount":80,"unit":"g"},{"name":"Vanilla","amount":1,"unit":"pod"},{"name":"Gelatin","amount":2,"unit":"sheets"},{"name":"Berries","amount":200,"unit":"g"}]', '["Bloom gelatin in cold water","Heat cream with vanilla and sugar","Add gelatin and stir to dissolve","Pour into molds","Chill for 4 hours","Unmold and serve with berries"]', 'chef_002', 'Chef Isabella',  '["italian","dessert","sweet"]'),

('recipe_048', 'Brownies', 'Fudgy chocolate brownies with crackly top.', 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800', 15, 25, 12, '[{"name":"Dark chocolate","amount":200,"unit":"g"},{"name":"Butter","amount":150,"unit":"g"},{"name":"Sugar","amount":200,"unit":"g"},{"name":"Eggs","amount":3,"unit":"pcs"},{"name":"Flour","amount":100,"unit":"g"},{"name":"Cocoa powder","amount":30,"unit":"g"}]', '["Melt chocolate and butter","Beat in sugar","Add eggs one at a time","Fold in flour and cocoa","Pour into lined pan","Bake at 180C for 25 minutes"]', 'chef_013', 'Chef Sarah',  '["american","dessert","chocolate","sweet"]'),

('recipe_049', 'Mango Sticky Rice', 'Thai dessert with sweet coconut rice and fresh mango.', 'https://images.unsplash.com/photo-1596451190630-186aff535bf2?w=800', 20, 30, 4, '[{"name":"Sticky rice","amount":300,"unit":"g"},{"name":"Coconut milk","amount":400,"unit":"ml"},{"name":"Sugar","amount":100,"unit":"g"},{"name":"Mangoes","amount":2,"unit":"pcs"},{"name":"Salt","amount":0.5,"unit":"tsp"}]', '["Soak sticky rice overnight","Steam until tender","Heat coconut milk with sugar and salt","Pour half over rice","Let absorb for 30 minutes","Serve with sliced mango and remaining sauce"]', 'chef_003', 'Chef Suki',  '["thai","asian","dessert","sweet","fruit"]'),

('recipe_050', 'Banana Bread', 'Moist and flavorful classic banana quick bread.', 'https://images.unsplash.com/photo-1605286978633-2dec93ff88a2?w=800', 15, 60, 10, '[{"name":"Ripe bananas","amount":4,"unit":"pcs"},{"name":"Flour","amount":280,"unit":"g"},{"name":"Sugar","amount":150,"unit":"g"},{"name":"Butter","amount":100,"unit":"g"},{"name":"Eggs","amount":2,"unit":"pcs"},{"name":"Baking soda","amount":1,"unit":"tsp"}]', '["Mash bananas well","Cream butter and sugar","Add eggs and banana","Fold in flour and baking soda","Pour into loaf pan","Bake at 175C for 55 minutes"]', 'chef_013', 'Chef Sarah',  '["american","dessert","sweet","frühstück"]')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url;
