import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';

/// User-specific theme and UI preferences (Prompt 5)
/// Stored in Supabase user_preferences table
class UserPreferencesModel extends Equatable {
  final String id;
  final String userId;
  
  // Theme Settings
  final String themeMode; // 'light', 'dark', 'system'
  final String themeVariant; // 'standard', 'true_black', 'high_contrast', 'warm', 'cool'
  final String accentColor; // Hex color code (#RRGGBB)
  
  // Timestamps
  final DateTime createdAt;
  final DateTime updatedAt;

  const UserPreferencesModel({
    required this.id,
    required this.userId,
    this.themeMode = 'system',
    this.themeVariant = 'standard',
    this.accentColor = '#2196F3', // Material Blue
    required this.createdAt,
    required this.updatedAt,
  });

  factory UserPreferencesModel.fromJson(Map<String, dynamic> json) {
    return UserPreferencesModel(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      themeMode: json['theme_mode'] as String? ?? 'system',
      themeVariant: json['theme_variant'] as String? ?? 'standard',
      accentColor: json['accent_color'] as String? ?? '#2196F3',
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'theme_mode': themeMode,
      'theme_variant': themeVariant,
      'accent_color': accentColor,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  UserPreferencesModel copyWith({
    String? id,
    String? userId,
    String? themeMode,
    String? themeVariant,
    String? accentColor,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return UserPreferencesModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      themeMode: themeMode ?? this.themeMode,
      themeVariant: themeVariant ?? this.themeVariant,
      accentColor: accentColor ?? this.accentColor,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  List<Object?> get props => [
        id,
        userId,
        themeMode,
        themeVariant,
        accentColor,
        createdAt,
        updatedAt,
      ];

  /// Convert theme mode string to ThemeMode enum
  ThemeMode get themeModeEnum {
    switch (themeMode) {
      case 'light':
        return ThemeMode.light;
      case 'dark':
        return ThemeMode.dark;
      case 'system':
      default:
        return ThemeMode.system;
    }
  }

  /// Convert accent color hex string to Color
  Color get accentColorValue {
    try {
      // Remove # if present
      final hex = accentColor.replaceFirst('#', '');
      // Parse hex string
      return Color(int.parse('FF$hex', radix: 16));
    } catch (e) {
      // Fallback to Material Blue if parsing fails
      return const Color(0xFF2196F3);
    }
  }

  /// Check if theme variant requires premium subscription
  bool get isAdvancedTheme {
    return themeVariant != 'standard';
  }

  /// Human-readable theme variant name
  String get themeVariantName {
    switch (themeVariant) {
      case 'true_black':
        return 'True Black (OLED)';
      case 'high_contrast':
        return 'High Contrast';
      case 'warm':
        return 'Warm';
      case 'cool':
        return 'Cool';
      case 'standard':
      default:
        return 'Standard';
    }
  }

  /// Create default preferences for a new user
  factory UserPreferencesModel.createDefault(String userId) {
    final now = DateTime.now();
    return UserPreferencesModel(
      id: '', // Will be generated by Supabase
      userId: userId,
      themeMode: 'system',
      themeVariant: 'standard',
      accentColor: '#2196F3',
      createdAt: now,
      updatedAt: now,
    );
  }
}
